

#define FILESYSTEM_CONSTS

const char *FILESYSTEM_CONSTS_FOLDER_READ = "FILESYSTEM_CONSTS_FOLDER_READ";
const char *FILESYSTEM_CONSTS_FILE_READ = "FILESYSTEM_CONSTS_FILE_READ";
const char *FILESYSTEM_CONSTS_FILE_WRITE = "FILESYSTEM_CONSTS_FILE_WRITE";
